### ISSUE TITLE
When closing a method explorer window with tabs, the changes are discarded without warning

### ISSUE THREAD

**Issue by VincentBlondeau** [dionisiydk/Calypso#238] opened 2018-04-13 20:29 UTC
(See: https://pharo.fogbugz.com/f/cases/21700/When-closing-a-method-explorer-window-with-tabs-the-changes-are-discarded-without-warning)

To reproduce:

Browse any method implementors, in the newly created window, change the method (add some code remove but do not save), browse the implementors of any message of this method, a new tab should open, then close the whole window. The changes are lost without warning.

And I lost some code ...

**Comment by dionisiydk** [comment] 2018-04-16 12:31
The problem is general with tabbed window. Closing main window does not ask tabs to allow it

**Comment by dionisiydk** [comment] 2018-04-16 12:33
It's same for manually created tabbed window group (from title menu of window)

**Comment by dionisiydk** [comment] 2018-04-16 12:49
So edit fogbugs description and I close this issue because it is not about Calypso

**Closed by dionisiydk** 2018-04-16 12:49 UTC
